# Generated by Django 4.1.3 on 2022-12-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0003_alter_profesor_segundo_apellido'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField()),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
                ('profesor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.profesor')),
            ],
        ),
    ]
