# Generated by Django 4.1.3 on 2022-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=120)),
                ('segundo_nombre', models.CharField(max_length=120)),
                ('primer_apellido', models.CharField(max_length=120)),
                ('segundo_apellido', models.CharField(max_length=120)),
            ],
        ),
    ]
