# Generated by Django 4.1.3 on 2022-12-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='segundo_nombre',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
